export const ON_REQUEST_LOGIN_OR_SIGN_UP = "ON_REQUEST_LOGIN_OR_SIGN_UP";
export const ON_REQUEST_LOGIN_OR_SIGN_UP_FINISHED =
  "ON_REQUEST_LOGIN_OR_SIGN_UP_FINISHED";

export const ON_AUTH_FORM_CHANGED = "ON_AUTH_FORM_CHANGED";
export const ON_TOGGLE_FORM_VIEW = "ON_TOGGLE_FORM_VIEW";
