export const FETCH_MY_WORK_SPACES = "FETCH_MY_WORK_SPACES";
export const FETCH_MY_WORK_SPACES_FINISHED = "FETCH_MY_WORK_SPACES_FINISHED";

export const ON_CREATE_WORK_SPACE = "ON_CREATE_WORK_SPACE";
export const ON_CREATE_WORK_SPACE_FINISHED = "ON_CREATE_WORK_SPACE_FINISHED";

export const TOGGLE_WORK_SPACE_FORM_VISIBLITY =
  "TOGGLE_WORK_SPACE_FORM_VISIBLITY";

export const WORK_SPACE_FORM_CHANGED = "WORK_SPACE_FORM_CHANGED";
